#!/usr/bin/env php
<?php
/**
 * Craft console bootstrap file
 */

use craft\helpers\App;

define('CRAFT_BASE_PATH', __DIR__);
define('CRAFT_VENDOR_PATH', CRAFT_BASE_PATH.'/vendor');

// Composer autoloader
require_once CRAFT_VENDOR_PATH.'/autoload.php';

// dotenv
if (class_exists('Dotenv\Dotenv') && file_exists(CRAFT_BASE_PATH.'/.env')) {
    Dotenv\Dotenv::create(CRAFT_BASE_PATH)->load();
}

if ($storagePath = App::env('CRAFT_STORAGE_PATH')) {
    define('CRAFT_STORAGE_PATH', $storagePath);
}

if ($keyPath = App::env('LICENSE_KEY_PATH')) {
    define('CRAFT_LICENSE_KEY_PATH', $keyPath);
}

define('CRAFT_ENVIRONMENT', App::env('CRAFT_ENV') ?: 'prod');

// Craft
$app = require CRAFT_VENDOR_PATH.'/craftcms/cms/bootstrap/console.php';
$exitCode = $app->run();
exit($exitCode);
